public partial class KeyString
{
  public const string KEY_IS_RANDOM_DATA = "KEY_IS_RANDOM_DATA";
  public const string KEY_MOVE_EGG_TICKETS_AMOUNT = "KEY_MOVE_EGG_TICKETS_AMOUNT";
  public const string KEY_MOVE_EGG_TICKETS_AMOUNT_NEEDCLAIM = "KEY_MOVE_EGG_TICKETS_AMOUNT_NEEDCLAIM";
  public const string KEY_CURRENT_NEED_SOLVING_EGG_ORDER_INDEX = "KEY_CURRENT_NEED_SOLVING_EGG_ORDER_INDEX";
  public const string KEY_CURRENT_EGG_GIFT_INDEX = "KEY_CURRENT_EGG_GIFT_INDEX";
#if !UNITY_EDITOR
  public const int KEY_DEFAULT_MOVE_EGG_TICKETS_AMOUNT = 5;
#endif
#if UNITY_EDITOR
  public const int KEY_DEFAULT_MOVE_EGG_TICKETS_AMOUNT = 1000;

#endif
  public const string KEY_DEFAULT_TUTORIAL_GAMEPLAY_EGG = "KEY_DEFAULT_TUTORIAL_GAMEPLAY_EGG";
  public const string KEY_DEFAULT_MOVE_TUTORIAL_GAMEPLAY_EGG = "KEY_DEFAULT_MOVE_TUTORIAL_GAMEPLAY_EGG";
}